name: Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: statcrypt
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Async Github Branch To Gitee
      uses: shanghaobo/github-branch-gitee@v1.0.0
      with:
        github_repo: dragoncqh/StrivingWiki
        github_branch: gh-pages
        gitee_repo: Changingway/StrivingWiki
        gitee_branch: gh-pages
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}
