# Actions基本工作流程注释#整个流程在master分支发生push事件时触发。
name: CI_master
# 控制工作流何时运行
'on':
  # 在推送或拉取请求事件上触发工作流程，但仅限于“main”分支
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]
  # 允许您从“操作”选项卡手动运行此工作流程
  workflow_dispatch:
# 环境变量设置
env:
  # 仓库名称
  REPO_NAME: StrivingWiki
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: statcrypt
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Async Github Branch To Gitee
      uses: shanghaobo/github-branch-gitee@v1.0.0
      with:
        github_repo: dragoncqh/StrivingWiki
        github_branch: gh-pages
        gitee_repo: Changingway/StrivingWiki
        gitee_branch: gh-pages
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}

#    - name: Build Gitee Pages
#      uses: yanglbme/gitee-pages-action@main
#      with:
#        # 注意替换为你的 Gitee 用户名
#        gitee-username: ${{ secrets.GITEE_USERNAME }}
#        # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
#        gitee-password: ${{ secrets.GITEE_PASSWORD }}
#        # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
#        gitee-repo: Changingway/StrivingWiki
#        # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
#        branch: gh-pages

#    - name: Mirror repo to Gitee.
#      uses: abersheeran/sync-gitee-mirror@v1-beta
#      with:
#        repository: Changingway/StrivingWiki
#        username: ${{ secrets.GITEE_USERNAME }}
#        password: ${{ secrets.GITEE_PASSWORD }}
